/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [LogDate]
      ,[LeftPain]
      ,[LeftNumb]
	  ,[RightPain]
      ,[RightNumb]
      ,[LeftElbowPain]
      ,[LeftElbowNumb]
      ,[Notes]
      ,[ExternalityAdjustment]
      ,[PeriodName]
  FROM [Tracking].[dbo].[NeckInj_wPeriod]